version: 2
registries:
  maven-repository-repo-bazaarvoice-com:
    type: maven-repository
    url: https://repo.bazaarvoice.com/nexus/content/groups/bazaarvoice/
    username: "${{secrets.SONATYPE_NEXUS_REPOSITORY_USERNAME}}"
    password: "${{secrets.SONATYPE_NEXUS_REPOSITORY_PASSWORD}}"

updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    rebase-strategy: "disabled"
    registries:
      - maven-repository-repo-bazaarvoice-com
